# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := Planar

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

Planar: 
	@echo "==== Building Planar ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f Planar.make

clean:
	@${MAKE} --no-print-directory -C . -f Planar.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Planar"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
